# Generated by Django 3.1.4 on 2020-12-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_session_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
