# Generated by Django 3.1.4 on 2020-12-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_new_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registered_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
