# Generated by Django 3.1.4 on 2020-12-25 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_registered_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='new_session_key',
        ),
    ]
