# Generated by Django 3.1.4 on 2020-12-24 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cultural Activities list',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='PlacementCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('address', models.CharField(default='', max_length=225)),
                ('city', models.CharField(default='', max_length=25)),
                ('state', models.CharField(default='', max_length=25)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Social Activities list',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sport list',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Trips list',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=225, null=True)),
                ('father_name', models.CharField(blank=True, default='', max_length=225, null=True)),
                ('mobile_number', models.CharField(blank=True, default='', max_length=14, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('age', models.IntegerField()),
                ('semester_or_year', models.CharField(blank=True, default='', max_length=225, null=True)),
                ('profile_submit_date', models.DateTimeField(auto_now_add=True)),
                ('cultural_activities_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.culturalactivity')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.department')),
                ('social_activities_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.socialactivity')),
                ('sports_participanted_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.sport')),
                ('trips_participanted_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.trip')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Student Profiles',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='Studentresume/img')),
                ('name', models.CharField(max_length=25)),
                ('father_name', models.CharField(max_length=25)),
                ('mobile', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('h_qualification', models.TextField()),
                ('trade', models.CharField(max_length=25)),
                ('work_experience', models.TextField()),
                ('projects', models.TextField()),
                ('achivement', models.TextField()),
                ('certification', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
                ('intrests', models.CharField(max_length=100)),
                ('submit_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Student Resumes',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announce_date', models.DateTimeField()),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('img', models.ImageField(upload_to='Announcements/img')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.department')),
            ],
            options={
                'verbose_name_plural': 'Announcements list',
            },
        ),
    ]
