# Generated by Django 3.1.4 on 2021-01-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='charges',
            field=models.CharField(blank=True, default='', max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='venue',
            field=models.CharField(blank=True, default='', max_length=225, null=True),
        ),
    ]
