# Generated by Django 3.1.4 on 2020-12-28 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20201228_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cultural_activities_in',
        ),
        migrations.RemoveField(
            model_name='student',
            name='social_activities_in',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sports_participanted_in',
        ),
        migrations.RemoveField(
            model_name='student',
            name='trips_participanted_in',
        ),
        migrations.AddField(
            model_name='culturalactivity',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.student'),
        ),
        migrations.AddField(
            model_name='socialactivity',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.student'),
        ),
        migrations.AddField(
            model_name='sport',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.student'),
        ),
        migrations.AddField(
            model_name='trip',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.student'),
        ),
    ]
