# Generated by Django 3.1.4 on 2021-01-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20210103_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='d_o_b',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='langauages',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
