# Generated by Django 3.1.4 on 2020-12-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_placementcompany_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cultural Activities',
            },
        ),
        migrations.CreateModel(
            name='SocialActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Social Activities',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Trips',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='cultural_activities_in',
            field=models.ManyToManyField(to='rest_api.CulturalActivity'),
        ),
        migrations.AddField(
            model_name='student',
            name='social_activities_in',
            field=models.ManyToManyField(to='rest_api.SocialActivity'),
        ),
        migrations.AddField(
            model_name='student',
            name='sports_participanted_in',
            field=models.ManyToManyField(to='rest_api.Sport'),
        ),
        migrations.AddField(
            model_name='student',
            name='trips_participanted_in',
            field=models.ManyToManyField(to='rest_api.Trip'),
        ),
    ]
