# Generated by Django 3.1.4 on 2020-12-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_auto_20201229_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalactivity',
            name='student',
            field=models.ManyToManyField(blank=True, to='rest_api.Student'),
        ),
        migrations.AlterField(
            model_name='socialactivity',
            name='student',
            field=models.ManyToManyField(blank=True, to='rest_api.Student'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='student',
            field=models.ManyToManyField(blank=True, to='rest_api.Student'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='student',
            field=models.ManyToManyField(blank=True, to='rest_api.Student'),
        ),
    ]
