# Generated by Django 3.1.4 on 2020-12-22 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_auto_20201222_0418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cultural_activities_in',
        ),
        migrations.AddField(
            model_name='student',
            name='cultural_activities_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.culturalactivity'),
        ),
        migrations.RemoveField(
            model_name='student',
            name='social_activities_in',
        ),
        migrations.AddField(
            model_name='student',
            name='social_activities_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.socialactivity'),
        ),
        migrations.RemoveField(
            model_name='student',
            name='sports_participanted_in',
        ),
        migrations.AddField(
            model_name='student',
            name='sports_participanted_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.sport'),
        ),
        migrations.RemoveField(
            model_name='student',
            name='trips_participanted_in',
        ),
        migrations.AddField(
            model_name='student',
            name='trips_participanted_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.trip'),
        ),
    ]
