# Generated by Django 3.1.4 on 2020-12-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_announcement_announce_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announce_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
