# Generated by Django 3.1.4 on 2020-12-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_auto_20201222_0420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Student Profiles'},
        ),
        migrations.AddField(
            model_name='resume',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='Studentresume/img'),
        ),
    ]
