# Generated by Django 3.1.4 on 2020-12-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_auto_20201229_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='img',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
