# Generated by Django 3.1.4 on 2020-12-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_auto_20201224_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='submit_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
