# Generated by Django 3.1.4 on 2020-12-29 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_auto_20201229_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.department'),
        ),
    ]
