# Generated by Django 3.1.4 on 2020-12-25 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_resume_submit_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name_plural': 'Announcements list'},
        ),
        migrations.AlterModelOptions(
            name='culturalactivity',
            options={'verbose_name_plural': 'Cultural Activities list'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name_plural': 'Student Resumes'},
        ),
        migrations.AlterModelOptions(
            name='socialactivity',
            options={'verbose_name_plural': 'Social Activities list'},
        ),
        migrations.AlterModelOptions(
            name='sport',
            options={'verbose_name_plural': 'Sport list'},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'verbose_name_plural': 'Trips list'},
        ),
    ]
