# Generated by Django 3.1.4 on 2021-01-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0011_auto_20210102_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
    ]
