# Generated by Django 3.1 on 2021-02-03 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_date', models.CharField(max_length=23)),
                ('response_message', models.TextField()),
                ('response_code', models.CharField(max_length=3)),
                ('txn_id', models.TextField()),
                ('txn_amount', models.CharField(max_length=9)),
                ('order_id', models.IntegerField()),
                ('status', models.CharField(max_length=12)),
                ('bank_txn_id', models.CharField(max_length=12)),
                ('Payment_mode', models.CharField(max_length=25)),
                ('gateway_name', models.CharField(max_length=25)),
                ('currency', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=8)),
                ('gateway_name', models.CharField(max_length=25)),
                ('response_message', models.TextField()),
                ('bank_name', models.CharField(max_length=25)),
                ('Payment_mode', models.CharField(max_length=25)),
                ('response_code', models.CharField(max_length=3)),
                ('txn_id', models.TextField()),
                ('txn_amount', models.CharField(max_length=9)),
                ('order_id', models.IntegerField()),
                ('status', models.CharField(max_length=12)),
                ('bank_txn_id', models.CharField(max_length=12)),
                ('txn_date', models.CharField(max_length=23)),
                ('refund_amount', models.IntegerField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RegisteredTrip', to='rest_api.trip')),
            ],
        ),
    ]
